print("=== Masukan Data Diri Anda ===\n")

nama = input("Masukan Nama Lengkap : ")
panggilan = input("Masukan Nama Panggilan : ")
umur = input("Masukan Umur : ")
jenis_kelamin = input("Masukan Jenis Kelamin : ")
alamat = input("Masukan Alamat : ")
tempat_lahir = input("Masukan Tempat Lahir : ")
tanggal_lahir = input("Masukan Tanggal Lahir : ")
bb = input("Masukan Berat Badan : ")
tb = input("Masukan Tinggi Badan : ")
warga_negara = input("Masukan Kewarganegaraan : ")
agama = input("Masukan Agama : ")
status = input("Masukan Status Perkawinan : ")
pendidikan = input("Masukan Pendidikan terakhir : ")
pekerjaan = input("Masukan Pekerjaan/Profesi : ")
instansi = input("Masukan Instansi : ")
goldar = input("Masukan Golongan Darah : ")
hobi = input("Masukan Hobi : ")
warna = input("Masukan Warna Favorit : ")
makanan = input("Masukan Makanan Favorit : ")
minuman = input("Masukan Minuman Favorit : ")

print("\n======== Data Diri ========\n")
print("Nama Lengkap        : ", nama)
print("Nama Panggilan      : ", panggilan)
print("Umur                : ", umur)
print("Jenis Kelamin       : ", jenis_kelamin)
print("Alamat              : ", alamat)
print("Tempat Lahir        : ", tempat_lahir)
print("Tanggal Lahir       : ", tanggal_lahir)
print("Berat Badan         : ", bb)
print("Tinggi Badan        : ", tb)
print("Kewarganegaraan     : ", warga_negara)
print("Agama               : ", agama)
print("Status Perkawinan   : ", status)
print("Pendidikan Terakhir : ", pendidikan)
print("Pekerjaan/Profesi   : ", pekerjaan)
print("Instansi            : ", instansi)
print("Golongan Darah      : ", goldar)
print("Hobi                : ", hobi)
print("Warna Favorit       : ", warna)
print("Makanan Favorit     : ", makanan)
print("Minuman Favorit     : ", minuman)



